### ISSUE TITLE
Problem with test demo

### ISSUE THREAD

**Issue by cgokce** [SijieSong/person_generation_spt#5]
Hi,

I have tried testing images with:
`bash ./scripts/test_demo.sh`

I have used my source and target images, and changed the coordinates from keypoints.csv. Then I have noticed that results have different behavior than only copying the target pose.

To confirm this, I have tried using the same source/target images and source/target poses(by also modifying keypoint.csv), the results were different! What is the cause of this problem? Why the same inputs give different result pose behavior? (maybe predetermined somewhere in code?)

If this problem is connected to demo, how can I test using my images?

**Filename 2A and 2B**
![2A-2B](https://user-images.githubusercontent.com/18016237/68436402-fbf13080-01ce-11ea-8ae3-e521cad63a91.png)

**Filename 3A and 3B**
![3A-3B](https://user-images.githubusercontent.com/18016237/68436405-fdbaf400-01ce-11ea-9724-40a78fbd25e9.png)

**Note:** I was using [Lotayou's](https://github.com/Lotayou/person_generation_spt) fork for python3 support.

**Comment by SijieSong** [comment]
Have you changed the segmentation? The output is also generated according to segmentation masks.

**Comment by cgokce** [comment]
No, I did not, that explains this behavior. I will also  change the masks(under `\parsing` folder) and report the result later. 

**Edit:** Results are consistent now. Thank you.


![2_A jpg_2_B jpg](https://user-images.githubusercontent.com/18016237/68516529-548b0100-0295-11ea-829f-df64fcff09b3.png)
![3_A jpg_3_B jpg](https://user-images.githubusercontent.com/18016237/68516532-548b0100-0295-11ea-9124-cad473c19440.png)
