### ISSUE TITLE
share the pre-models in Baidu Yun?

### ISSUE THREAD

**Issue by freelily** [SijieSong/person_generation_spt#7]
Could you pls share the pre-models in Baidu Yun?
As we are in China, can't use google driver. Thank you.

**Comment by SijieSong** [comment]
> Could you pls share the pre-models in Baidu Yun?
> As we are in China, can't use google driver. Thank you.

Please find the model at https://pan.baidu.com/s/15PCwbr4ayFcxnKlArwHjgw
Thanks.
